run:
  timeout: 3m
  go: "1.21"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
  disable:
    - exhaustruct

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
  goimports:
    local-prefixes: github.com/samhotchkiss/otter-camp

issues:
  exclude-rules:
    - path: _test\.go
      linters: [revive]
    - path: internal/db/migrations/
      linters: [gofmt, goimports]
