INSERT INTO tool_definition (
    name,
    display_name,
    description,
    tool_tier,
    tool_domain,
    required_capability,
    input_schema,
    is_enabled
) VALUES
    ('file.write', 'File Write', 'Write a file in the session workspace', 'tier2', 'native', 'system.file.write', '{"type":"object"}'::jsonb, true),
    ('file.edit', 'File Edit', 'Edit file contents by replacing a target string', 'tier2', 'native', 'system.file.write', '{"type":"object"}'::jsonb, true),
    ('file.delete', 'File Delete', 'Delete a file in the session workspace', 'tier2', 'native', 'system.file.write', '{"type":"object"}'::jsonb, true),
    ('git.commit', 'Git Commit', 'Stage and commit repository changes', 'tier2', 'native', 'system.file.write', '{"type":"object"}'::jsonb, true),
    ('git.push', 'Git Push', 'Push commits to a git remote', 'tier2', 'native', 'system.git.push', '{"type":"object"}'::jsonb, true),
    ('cli.execute', 'CLI Execute', 'Execute a CLI command via the CLI executor', 'tier2', 'native', 'system.cli.execute', '{"type":"object"}'::jsonb, true),
    ('memory.record', 'Memory Record', 'Record explicit memory content', 'tier2', 'native', 'memory.write', '{"type":"object"}'::jsonb, true),
    ('project.create', 'Project Create', 'Create a project', 'tier2', 'native', 'project.manage', '{"type":"object"}'::jsonb, true),
    ('project.update', 'Project Update', 'Update a project', 'tier2', 'native', 'project.manage', '{"type":"object"}'::jsonb, true),
    ('task.create', 'Task Create', 'Create a task', 'tier2', 'native', 'task.manage', '{"type":"object"}'::jsonb, true),
    ('task.update', 'Task Update', 'Update a task', 'tier2', 'native', 'task.manage', '{"type":"object"}'::jsonb, true),
    ('task.add_dependency', 'Task Add Dependency', 'Add a task or subtask dependency edge', 'tier2', 'native', 'task.manage', '{"type":"object"}'::jsonb, true),
    ('task.remove_dependency', 'Task Remove Dependency', 'Remove a task or subtask dependency edge', 'tier2', 'native', 'task.manage', '{"type":"object"}'::jsonb, true),
    ('subtask.create', 'Subtask Create', 'Create a subtask for a flow node execution', 'tier2', 'native', 'task.manage', '{"type":"object"}'::jsonb, true),
    ('subtask.update', 'Subtask Update', 'Update a subtask', 'tier2', 'native', 'task.manage', '{"type":"object"}'::jsonb, true),
    ('flow.advance', 'Flow Advance', 'Advance a flow execution to the next node', 'tier2', 'native', 'flow.control', '{"type":"object"}'::jsonb, true),
    ('flow.review_decision', 'Flow Review Decision', 'Record approve/reject decision for flow review', 'tier2', 'native', 'flow.control', '{"type":"object"}'::jsonb, true),
    ('flow.create_template', 'Flow Create Template', 'Create a flow template', 'tier2', 'native', 'project.manage', '{"type":"object"}'::jsonb, true),
    ('schedule.create', 'Schedule Create', 'Create a project schedule', 'tier2', 'native', 'project.manage', '{"type":"object"}'::jsonb, true),
    ('schedule.update', 'Schedule Update', 'Update a project schedule', 'tier2', 'native', 'project.manage', '{"type":"object"}'::jsonb, true),
    ('schedule.delete', 'Schedule Delete', 'Delete a project schedule', 'tier2', 'native', 'project.manage', '{"type":"object"}'::jsonb, true),
    ('agent.create_temp', 'Agent Create Temp', 'Create a temporary project-scoped agent', 'tier2', 'native', 'agent.create_temp', '{"type":"object"}'::jsonb, true),
    ('agent.update', 'Agent Update', 'Update an agent profile', 'tier2', 'native', 'agent.manage', '{"type":"object"}'::jsonb, true),
    ('session.create', 'Session Create', 'Create a chat session', 'tier2', 'native', 'session.manage', '{"type":"object"}'::jsonb, true),
    ('session.invite_agent', 'Session Invite Agent', 'Invite an agent into a chat session', 'tier2', 'native', 'session.manage', '{"type":"object"}'::jsonb, true),
    ('message.send', 'Message Send', 'Send a chat message into a session', 'tier2', 'native', 'message.send', '{"type":"object"}'::jsonb, true),
    ('email.compose', 'Email Compose', 'Compose an email draft requiring review', 'tier2', 'native', 'communication.send', '{"type":"object"}'::jsonb, true),
    ('slack.post', 'Slack Post', 'Compose a Slack post draft requiring review', 'tier2', 'native', 'communication.send', '{"type":"object"}'::jsonb, true)
ON CONFLICT (name) DO NOTHING;
