DROP POLICY IF EXISTS project_issue_comments_org_isolation ON project_issue_comments;
DROP TRIGGER IF EXISTS project_issue_comments_updated_at_trg ON project_issue_comments;
DROP INDEX IF EXISTS project_issue_comments_issue_created_idx;
DROP TABLE IF EXISTS project_issue_comments;

DROP POLICY IF EXISTS project_issue_participants_org_isolation ON project_issue_participants;
DROP INDEX IF EXISTS project_issue_participants_issue_active_idx;
DROP INDEX IF EXISTS project_issue_participants_owner_unique_idx;
DROP INDEX IF EXISTS project_issue_participants_active_unique_idx;
DROP TABLE IF EXISTS project_issue_participants;
