ALTER TABLE agents
    ADD COLUMN IF NOT EXISTS role TEXT,
    ADD COLUMN IF NOT EXISTS emoji TEXT,
    ADD COLUMN IF NOT EXISTS soul_md TEXT,
    ADD COLUMN IF NOT EXISTS identity_md TEXT,
    ADD COLUMN IF NOT EXISTS instructions_md TEXT;
