#!/usr/bin/env bash
set -euo pipefail

bold="\033[1m"
green="\033[0;32m"
yellow="\033[0;33m"
red="\033[0;31m"
reset="\033[0m"

check_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo -e "${red}ERROR${reset} missing required command: ${cmd}"
    exit 1
  fi
  echo -e "${green}OK${reset} ${cmd}"
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi

  # Fallback for environments without openssl.
  date +%s%N | shasum | awk '{print $1}'
}

echo -e "${bold}Otter Camp local setup${reset}"
echo

check_cmd go
check_cmd node
check_cmd npm
check_cmd git

use_docker=false
compose_cmd=""
if command -v docker >/dev/null 2>&1; then
  if docker compose version >/dev/null 2>&1; then
    use_docker=true
    compose_cmd="docker compose"
    echo -e "${green}OK${reset} docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    use_docker=true
    compose_cmd="docker-compose"
    echo -e "${green}OK${reset} docker-compose"
  fi
fi

if [[ "${use_docker}" == "false" ]]; then
  if command -v psql >/dev/null 2>&1; then
    echo -e "${yellow}WARN${reset} docker unavailable; expecting local postgres via DATABASE_URL"
  else
    echo -e "${red}ERROR${reset} install Docker (with compose) or PostgreSQL client (psql)."
    exit 1
  fi
fi

if [[ ! -f .env ]]; then
  sync_secret="$(generate_secret)"
  ws_secret="$(generate_secret)"
  webhook_secret="$(generate_secret)"
  auth_secret="$(generate_secret)"
  local_auth_token="oc_local_$(generate_secret | cut -c1-32)"

  cat > .env <<EOF
# Generated by scripts/setup.sh on $(date)
APP_ENV=development
PORT=8080
DATABASE_URL=postgres://otter:camp@localhost:5432/ottercamp?sslmode=disable
OPENCLAW_WEBHOOK_SECRET=${webhook_secret}
OPENCLAW_WS_SECRET=${ws_secret}
OPENCLAW_SYNC_SECRET=${sync_secret}
OPENCLAW_SYNC_TOKEN=${sync_secret}
OPENCLAW_AUTH_SECRET=${auth_secret}
LOCAL_AUTH_TOKEN=${local_auth_token}
VITE_API_URL=http://localhost:8080
GIT_REPO_ROOT=./data/repos
EOF
  echo -e "${green}OK${reset} created .env"
else
  echo -e "${green}OK${reset} .env already exists (not overwritten)"
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

if [[ "${use_docker}" == "true" ]]; then
  echo "Starting postgres..."
  ${compose_cmd} up -d postgres >/dev/null

  ready=0
  for _ in $(seq 1 60); do
    if docker exec otter-camp-db pg_isready -U otter -d ottercamp >/dev/null 2>&1; then
      ready=1
      break
    fi
    sleep 1
  done
  if [[ "${ready}" != "1" ]]; then
    echo -e "${red}ERROR${reset} postgres did not become ready in time"
    exit 1
  fi
  echo -e "${green}OK${reset} postgres is ready"
fi

mkdir -p data/repos
echo -e "${green}OK${reset} ensured data/repos exists"

echo "Running migrations..."
go run ./cmd/migrate up
echo -e "${green}OK${reset} migrations applied"

echo "Installing frontend dependencies..."
(cd web && npm ci --silent)
echo -e "${green}OK${reset} web dependencies installed"

echo "Seeding default workspace..."
go run ./scripts/seed/seed.go
echo -e "${green}OK${reset} seed complete"

if [[ "$(uname -s)" == "Darwin" ]]; then
  otter_cfg_dir="${HOME}/Library/Application Support/otter"
else
  otter_cfg_dir="${XDG_CONFIG_HOME:-${HOME}/.config}/otter"
fi
mkdir -p "${otter_cfg_dir}"
cat > "${otter_cfg_dir}/config.json" <<EOF
{
  "apiBaseUrl": "http://localhost:8080",
  "token": "${LOCAL_AUTH_TOKEN}",
  "defaultOrg": ""
}
EOF
echo -e "${green}OK${reset} wrote CLI config to ${otter_cfg_dir}/config.json"

mkdir -p bridge
if [[ ! -f bridge/.env ]]; then
  cat > bridge/.env <<EOF
# Generated by scripts/setup.sh
OPENCLAW_HOST=127.0.0.1
OPENCLAW_PORT=18791
OPENCLAW_TOKEN=your-openclaw-gateway-token
OTTERCAMP_URL=http://localhost:8080
OTTERCAMP_TOKEN=${OPENCLAW_SYNC_SECRET}
OPENCLAW_WS_SECRET=${OPENCLAW_WS_SECRET}
EOF
  echo -e "${green}OK${reset} created bridge/.env (set OPENCLAW_TOKEN before running bridge)"
else
  echo -e "${green}OK${reset} bridge/.env already exists (not overwritten)"
fi

echo
echo -e "${bold}Setup complete.${reset}"
echo "Run: make dev"
echo "UI:  http://localhost:5173"
echo "API: http://localhost:8080"
